on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: 
          - deployment/inference
          - deployment/serving_api
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: run tox
        run: |
          cd ${{ matrix.path }}
          tox -e checks